use_frameworks!
platform :ios, '14.0'


# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseIM' do

    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'TFHpple'

    pod 'AgoraRtcEngine_iOS/RtcBasic'
    pod 'FMDB'
    pod 'HyphenateChat', '4.2.0'
#    pod 'EaseIMKit'
    pod 'EaseCallKit'

#    pod 'EaseIMKit', '4.2.0'

  pod 'EaseIMKit', :git => 'git@github.com:Jacky-LinPeng/easeui_ios.git'

    pod 'Bugly'
    
    pod 'lottie-ios','4.3.3'
    pod 'OpenAISwift', :git => 'git@github.com:Jacky-LinPeng/OpenAISwift.git'
    
    
#    xcode 14打开这个
    post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
                config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
             end
        end
      end
    end
    
end

