# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatAi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'HyphenateChat'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyFitsize'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'SQLite.swift'
  pod 'Toast-Swift'
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
           end
      end
    end
  end
  
end
