import 'dart:ui';

import 'package:base_ui/base_ui.dart';
import 'package:flutter/widgets.dart';

class LibFonts {
  static const String libDefaultIcomoon = 'defaultIcomoon';
}

class LibColors {


  static const Color libErrorColor = Color(0xffD50000);
  static const Color libInfoColor = Color(0xff3F51B5);
  static const Color libSuccessColor = Color(0xff388E3C);
  static const Color libWarningColor = Color(0xffFFA900);
  static const Color libTransparent = Color(0x00000000);
  static const Color divider = Color(0xffe5e5e5);
  static const Color libColorWhite = Color(0xffffffff);// 白色
  static const Color libColorIvory = Color(0xfffffff0);// 象牙色 
  static const Color libColorLightyellow = Color(0xffffffe0);// 亮黄色 
  static const Color libColorYellow = Color(0xffffff00);// 黄色 
  static const Color libColorSnow = Color(0xfffffafa);// 雪白色 
  static const Color libColorFloralwhite = Color(0xfffffaf0);// 花白色 
  static const Color libColorLemonchiffon = Color(0xfffffacd);// 柠檬绸色 
  static const Color libColorCornsilk = Color(0xfffff8dc);// 米绸色 
  static const Color libColorSeaShell = Color(0xfffff5ee);// 海贝色 
  static const Color libColorLavenderblush = Color(0xfffff0f5);// 淡紫红 
  static const Color libColorpapayawhip = Color(0xffffefd5);// 番木色 
  static const Color libColorBlanchedalmond = Color(0xffffebcd);// 白杏色 
  static const Color libColorMistyrose = Color(0xffffe4e1);// 浅玫瑰色 
  static const Color libColorBisque = Color(0xffffe4c4);// 桔黄色 
  static const Color libColorMoccasin = Color(0xffffe4b5);// 鹿皮色 
  static const Color libColorNavajowhite = Color(0xffffdead);// 纳瓦白 
  static const Color libColorpeachpuff = Color(0xffffdab9);// 桃色 
  static const Color libColorGold = Color(0xffffd700);// 金色 
  static const Color libColorpink = Color(0xffffc0cb);// 粉红色 
  static const Color libColorLightpink = Color(0xffffb6c1);// 亮粉红色 
  static const Color libColorOrange = Color(0xffffa500);// 橙色 
  static const Color libColorLightsalmon = Color(0xffffa07a);// 亮肉色 
  static const Color libColorDarkorange = Color(0xffff8c00);// 暗桔黄色 
  static const Color libColorCoral = Color(0xffff7f50);// 珊瑚色 
  static const Color libColorHotpink = Color(0xffff69b4);// 热粉红色 
  static const Color libColorTomato = Color(0xffff6347);// 西红柿色 
  static const Color libColorOrangered = Color(0xffff4500);// 红橙色 
  static const Color libColorDeeppink = Color(0xffff1493);// 深粉红色 
  static const Color libColorFuchsia = Color(0xffff00ff);// 紫红色 
  static const Color libColorMagenta = Color(0xffff00ff);// 红紫色 
  static const Color libColorRed = Color(0xffff0000);// 红色 
  static const Color libColorOldlace = Color(0xfffdf5e6);// 老花色 
  static const Color libColorLightgoldenrodyellow = Color(0xfffafad2);// 亮金黄色 
  static const Color libColorLinen = Color(0xfffaf0e6);// 亚麻色 
  static const Color libColorAntiquewhite = Color(0xfffaebd7);// 古董白 
  static const Color libColorSalmon = Color(0xfffa8072);// 鲜肉色 
  static const Color libColorGhostwhite = Color(0xfff8f8ff);// 幽灵白 
  static const Color libColorMintcream = Color(0xfff5fffa);// 薄荷色 
  static const Color libColorWhitesmoke = Color(0xfff5f5f5);// 烟白色 
  static const Color libColorBeige = Color(0xfff5f5dc);// 米色 
  static const Color libColorWheat = Color(0xfff5deb3);// 浅黄色 
  static const Color libColorSandybrown = Color(0xfff4a460);// 沙褐色 
  static const Color libColorAzure = Color(0xfff0ffff);// 天蓝色 
  static const Color libColorHoneydew = Color(0xfff0fff0);// 蜜色 
  static const Color libColorAliceblue = Color(0xfff0f8ff);// 艾利斯兰 
  static const Color libColorKhaki = Color(0xfff0e68c);// 黄褐色 
  static const Color libColorLightcoral = Color(0xfff08080);// 亮珊瑚色 
  static const Color libColorpalegoldenrod = Color(0xffeee8aa);// 苍麒麟色 
  static const Color libColorViolet = Color(0xffee82ee);// 紫罗兰色 
  static const Color libColorDarksalmon = Color(0xffe9967a);// 暗肉色 
  static const Color libColorLavender = Color(0xffe6e6fa);// 淡紫色 
  static const Color libColorLightcyan = Color(0xffe0ffff);// 亮青色 
  static const Color libColorBurlywood = Color(0xffdeb887);// 实木色 
  static const Color libColorplum = Color(0xffdda0dd);// 洋李色 
  static const Color libColorGainsboro = Color(0xffdcdcdc);// 淡灰色 
  static const Color libColorCrimson = Color(0xffdc143c);// 暗深红色 
  static const Color libColorpalevioletred = Color(0xffdb7093);// 苍紫罗兰色 
  static const Color libColorGoldenrod = Color(0xffdaa520);// 金麒麟色 
  static const Color libColorOrchid = Color(0xffda70d6);// 淡紫色 
  static const Color libColorThistle = Color(0xffd8bfd8);// 蓟色 
  static const Color libColorLightgray = Color(0xffd3d3d3);// 亮灰色 
  static const Color libColorLightgrey = Color(0xffd3d3d3);// 亮灰色 
  static const Color libColorTan = Color(0xffd2b48c);// 茶色 
  static const Color libColorChocolate = Color(0xffd2691e);// 巧可力色 
  static const Color libColorperu = Color(0xffcd853f);// 秘鲁色 
  static const Color libColorIndianred = Color(0xffcd5c5c);// 印第安红 
  static const Color libColorMediumvioletred = Color(0xffc71585);// 中紫罗兰色 
  static const Color libColorSilver = Color(0xffc0c0c0);// 银色 
  static const Color libColorDarkkhaki = Color(0xffbdb76b);// 暗黄褐色 
  static const Color libColorRosybrown = Color(0xffbc8f8f);// 褐玫瑰红 
  static const Color libColorMediumorchid = Color(0xffba55d3);// 中粉紫色 
  static const Color libColorDarkgoldenrod = Color(0xffb8860b);// 暗金黄色 
  static const Color libColorFirebrick = Color(0xffb22222);// 火砖色 
  static const Color libColorpowderblue = Color(0xffb0e0e6);// 粉蓝色 
  static const Color libColorLightsteelblue = Color(0xffb0c4de);// 亮钢兰色 
  static const Color libColorpaleturquoise = Color(0xffafeeee);// 苍宝石绿 
  static const Color libColorGreenyellow = Color(0xffadff2f);// 黄绿色 
  static const Color libColorLightblue = Color(0xffadd8e6);// 亮蓝色 
  static const Color libColorDarkgray = Color(0xffa9a9a9);// 暗灰色 
  static const Color libColorDarkgrey = Color(0xffa9a9a9);// 暗灰色 
  static const Color libColorBrown = Color(0xffa52a2a);// 褐色 
  static const Color libColorSienna = Color(0xffa0522d);// 赭色 
  static const Color libColorDarkorchid = Color(0xff9932cc);// 暗紫色 
  static const Color libColorpalegreen = Color(0xff98fb98);// 苍绿色 
  static const Color libColorDarkviolet = Color(0xff9400d3);// 暗紫罗兰色 
  static const Color libColorMediumpurple = Color(0xff9370db);// 中紫色 
  static const Color libColorLightgreen = Color(0xff90ee90);// 亮绿色 
  static const Color libColorDarkseagreen = Color(0xff8fbc8f);// 暗海兰色 
  static const Color libColorSaddlebrown = Color(0xff8b4513);// 重褐色 
  static const Color libColorDarkmagenta = Color(0xff8b008b);// 暗洋红 
  static const Color libColorDarkred = Color(0xff8b0000);// 暗红色 
  static const Color libColorBlueviolet = Color(0xff8a2be2);// 紫罗兰蓝色 
  static const Color libColorLightskyblue = Color(0xff87cefa);// 亮天蓝色 
  static const Color libColorSkyblue = Color(0xff87ceeb);// 天蓝色 
  static const Color libColorGray = Color(0xff808080);// 灰色 
  static const Color libColorGrey = Color(0xff808080);// 灰色 
  static const Color libColorOlive = Color(0xff808000);// 橄榄色 
  static const Color libColorpurple = Color(0xff800080);// 紫色 
  static const Color libColorMaroon = Color(0xff800000);// 粟色 
  static const Color libColorAquamarine = Color(0xff7fffd4);// 碧绿色 
  static const Color libColorChartreuse = Color(0xff7fff00);// 黄绿色 
  static const Color libColorLawngreen = Color(0xff7cfc00);// 草绿色 
  static const Color libColorMediumslateblue = Color(0xff7b68ee);// 中暗蓝色 
  static const Color libColorLightslategray = Color(0xff778899);// 亮蓝灰 
  static const Color libColorLightslategrey = Color(0xff778899);// 亮蓝灰 
  static const Color libColorSlategray = Color(0xff708090);// 灰石色 
  static const Color libColorSlategrey = Color(0xff708090);// 灰石色 
  static const Color libColorOlivedrab = Color(0xff6b8e23);// 深绿褐色 
  static const Color libColorSlateblue = Color(0xff6a5acd);// 石蓝色 
  static const Color libColorDimgray = Color(0xff696969);// 暗灰色 
  static const Color libColorDimgrey = Color(0xff696969);// 暗灰色 
  static const Color libColorMediumaquamarine = Color(0xff66cdaa);// 中绿色 
  static const Color libColorCornflowerblue = Color(0xff6495ed);// 菊兰色 
  static const Color libColorCadetblue = Color(0xff5f9ea0);// 军兰色 
  static const Color libColorDarkolivegreen = Color(0xff556b2f);// 暗橄榄绿 
  static const Color libColorIndigo = Color(0xff4b0082);// 靛青色 
  static const Color libColorMediumturquoise = Color(0xff48d1cc);// 中绿宝石 
  static const Color libColorDarkslateblue = Color(0xff483d8b);// 暗灰蓝色 
  static const Color libColorSteelblue = Color(0xff4682b4);// 钢兰色 
  static const Color libColorRoyalblue = Color(0xff4169e1);// 皇家蓝 
  static const Color libColorTurquoise = Color(0xff40e0d0);// 青绿色 
  static const Color libColorMediumseagreen = Color(0xff3cb371);// 中海蓝 
  static const Color libColorLimegreen = Color(0xff32cd32);// 橙绿色 
  static const Color libColorDarkslategray = Color(0xff2f4f4f);// 暗瓦灰色 
  static const Color libColorDarkslategrey = Color(0xff2f4f4f);// 暗瓦灰色 
  static const Color libColorSeagreen = Color(0xff2e8b57);// 海绿色 
  static const Color libColorForestgreen = Color(0xff228b22);// 森林绿 
  static const Color libColorLightseagreen = Color(0xff20b2aa);// 亮海蓝色 
  static const Color libColorDodgerblue = Color(0xff1e90ff);// 闪兰色 
  static const Color libColorMidnightblue = Color(0xff191970);// 中灰兰色 
  static const Color libColorAqua = Color(0xff00ffff);// 浅绿色 
  static const Color libColorCyan = Color(0xff00ffff);// 青色 
  static const Color libColorSpringgreen = Color(0xff00ff7f);// 春绿色 
  static const Color libColorLime = Color(0xff00ff00);// 酸橙色 
  static const Color libColorMediumspringgreen = Color(0xff00fa9a);// 中春绿色 
  static const Color libColorDarkturquoise = Color(0xff00ced1);// 暗宝石绿 
  static const Color libColorDeepskyblue = Color(0xff00bfff);// 深天蓝色 
  static const Color libColorDarkcyan = Color(0xff008b8b);// 暗青色 
  static const Color libColorTeal = Color(0xff008080);// 水鸭色 
  static const Color libColorGreen = Color(0xff008000);// 绿色 
  static const Color libColorDarkgreen = Color(0xff006400);// 暗绿色 
  static const Color libColorBlue = Color(0xff0000ff);// 蓝色 
  static const Color libColorMediumblue = Color(0xff0000cd);// 中兰色 
  static const Color libColorDarkblue = Color(0xff00008b);// 暗蓝色 
  static const Color libColorNavy = Color(0xff000080);// 海军色 
  static const Color libColorBlack = Color(0xff000000);// 黑色 
  static const Color libColorGrey1 = Color(0xff999999);// 灰色 
}

class LibSize {

}

class LibStyle {
  static const libLine = 0.5;
  static const libline1 = 1;
}

class LibIconFonts {
  // 字体图标 start
  static const IconData libIconHome = IconData(0xe900, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHome2 =IconData(0xe901, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHome3 =IconData(0xe902, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconOffice =IconData(0xe903, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNewspaper =IconData(0xe904, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpencil =IconData(0xe905, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpencil2 =IconData(0xe906, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconQuill =IconData(0xe907, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpen =IconData(0xe908, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBlog =IconData(0xe909, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEyedropper =IconData(0xe90a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDroplet =IconData(0xe90b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpaintFormat =IconData(0xe90c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconImage =IconData(0xe90d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconImages =IconData(0xe90e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCamera =IconData(0xe90f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHeadphones =IconData(0xe910, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMusic =IconData(0xe911, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconplay =IconData(0xe912, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFilm =IconData(0xe913, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVideoCamera =IconData(0xe914, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDice =IconData(0xe915, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpacman =IconData(0xe916, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpades =IconData(0xe917, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconClubs =IconData(0xe918, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDiamonds =IconData(0xe919, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBullhorn =IconData(0xe91a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconConnection =IconData(0xe91b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpodcast =IconData(0xe91c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFeed =IconData(0xe91d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMic =IconData(0xe91e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBook =IconData(0xe91f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBooks =IconData(0xe920, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLibrary =IconData(0xe921, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileText =IconData(0xe922, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconprofile =IconData(0xe923, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileEmpty =IconData(0xe924, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFilesEmpty =IconData(0xe925, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileText2 =IconData(0xe926, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFilepicture =IconData(0xe927, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileMusic =IconData(0xe928, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileplay =IconData(0xe929, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileVideo =IconData(0xe92a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileZip =IconData(0xe92b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCopy =IconData(0xe92c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpaste =IconData(0xe92d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStack =IconData(0xe92e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFolder =IconData(0xe92f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFolderOpen =IconData(0xe930, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFolderplus =IconData(0xe931, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFolderMinus =IconData(0xe932, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFolderDownload =IconData(0xe933, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFolderUpload =IconData(0xe934, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpriceTag =IconData(0xe935, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpriceTags =IconData(0xe936, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBarcode =IconData(0xe937, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconQrcode =IconData(0xe938, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTicket =IconData(0xe939, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCart =IconData(0xe93a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCoinDollar =IconData(0xe93b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCoinEuro =IconData(0xe93c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCoinpound =IconData(0xe93d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCoinYen =IconData(0xe93e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCreditCard =IconData(0xe93f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCalculator =IconData(0xe940, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLifebuoy =IconData(0xe941, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconphone =IconData(0xe942, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconphoneHangUp =IconData(0xe943, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAddressBook =IconData(0xe944, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEnvelop =IconData(0xe945, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpushpin =IconData(0xe946, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLocation =IconData(0xe947, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLocation2 =IconData(0xe948, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCompass =IconData(0xe949, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCompass2 =IconData(0xe94a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMap =IconData(0xe94b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMap2 =IconData(0xe94c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHistory =IconData(0xe94d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconClock =IconData(0xe94e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconClock2 =IconData(0xe94f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAlarm =IconData(0xe950, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBell =IconData(0xe951, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStopwatch =IconData(0xe952, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCalendar =IconData(0xe953, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconprinter =IconData(0xe954, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconKeyboard =IconData(0xe955, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDisplay =IconData(0xe956, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLaptop =IconData(0xe957, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMobile =IconData(0xe958, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMobile2 =IconData(0xe959, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTablet =IconData(0xe95a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTv =IconData(0xe95b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDrawer =IconData(0xe95c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDrawer2 =IconData(0xe95d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBoxAdd =IconData(0xe95e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBoxRemove =IconData(0xe95f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDownload =IconData(0xe960, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUpload =IconData(0xe961, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFloppyDisk =IconData(0xe962, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDrive =IconData(0xe963, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDatabase =IconData(0xe964, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUndo =IconData(0xe965, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRedo =IconData(0xe966, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUndo2 =IconData(0xe967, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRedo2 =IconData(0xe968, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconForward =IconData(0xe969, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconReply =IconData(0xe96a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBubble =IconData(0xe96b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBubbles =IconData(0xe96c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBubbles2 =IconData(0xe96d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBubble2 =IconData(0xe96e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBubbles3 =IconData(0xe96f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBubbles4 =IconData(0xe970, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUser =IconData(0xe971, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUsers =IconData(0xe972, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUserplus =IconData(0xe973, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUserMinus =IconData(0xe974, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUserCheck =IconData(0xe975, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUserTie =IconData(0xe976, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconQuotesLeft =IconData(0xe977, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconQuotesRight =IconData(0xe978, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHourGlass =IconData(0xe979, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner =IconData(0xe97a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner2 =IconData(0xe97b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner3 =IconData(0xe97c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner4 =IconData(0xe97d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner5 =IconData(0xe97e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner6 =IconData(0xe97f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner7 =IconData(0xe980, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner8 =IconData(0xe981, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner9 =IconData(0xe982, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner10 =IconData(0xe983, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpinner11 =IconData(0xe984, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBinoculars =IconData(0xe985, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSearch =IconData(0xe986, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconZoomIn =IconData(0xe987, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconZoomOut =IconData(0xe988, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEnlarge =IconData(0xe989, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShrink =IconData(0xe98a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEnlarge2 =IconData(0xe98b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShrink2 =IconData(0xe98c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconKey =IconData(0xe98d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconKey2 =IconData(0xe98e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLock =IconData(0xe98f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUnlocked =IconData(0xe990, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWrench =IconData(0xe991, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEqualizer =IconData(0xe992, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEqualizer2 =IconData(0xe993, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCog =IconData(0xe994, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCogs =IconData(0xe995, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHammer =IconData(0xe996, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMagicWand =IconData(0xe997, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAidKit =IconData(0xe998, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBug =IconData(0xe999, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpieChart =IconData(0xe99a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStatsDots =IconData(0xe99b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStatsBars =IconData(0xe99c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStatsBars2 =IconData(0xe99d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTrophy =IconData(0xe99e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGift =IconData(0xe99f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGlass =IconData(0xe9a0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGlass2 =IconData(0xe9a1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMug =IconData(0xe9a2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpoonKnife =IconData(0xe9a3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLeaf =IconData(0xe9a4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRocket =IconData(0xe9a5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMeter =IconData(0xe9a6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMeter2 =IconData(0xe9a7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHammer2 =IconData(0xe9a8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFire =IconData(0xe9a9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLab =IconData(0xe9aa, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMagnet =IconData(0xe9ab, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBin =IconData(0xe9ac, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBin2 =IconData(0xe9ad, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBriefcase =IconData(0xe9ae, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAirplane =IconData(0xe9af, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTruck =IconData(0xe9b0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRoad =IconData(0xe9b1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAccessibility =IconData(0xe9b2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTarget =IconData(0xe9b3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShield =IconData(0xe9b4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpower =IconData(0xe9b5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSwitchs =IconData(0xe9b6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpowerCord =IconData(0xe9b7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconClipboard =IconData(0xe9b8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconListNumbered =IconData(0xe9b9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconList =IconData(0xe9ba, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconList2 =IconData(0xe9bb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTree =IconData(0xe9bc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMenu =IconData(0xe9bd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMenu2 =IconData(0xe9be, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMenu3 =IconData(0xe9bf, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMenu4 =IconData(0xe9c0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCloud =IconData(0xe9c1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCloudDownload =IconData(0xe9c2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCloudUpload =IconData(0xe9c3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCloudCheck =IconData(0xe9c4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDownload2 =IconData(0xe9c5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUpload2 =IconData(0xe9c6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDownload3 =IconData(0xe9c7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUpload3 =IconData(0xe9c8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSphere =IconData(0xe9c9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEarth =IconData(0xe9ca, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLink =IconData(0xe9cb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFlag =IconData(0xe9cc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAttachment =IconData(0xe9cd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEye =IconData(0xe9ce, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEyeplus =IconData(0xe9cf, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEyeMinus =IconData(0xe9d0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEyeBlocked =IconData(0xe9d1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBookmark =IconData(0xe9d2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBookmarks =IconData(0xe9d3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSun =IconData(0xe9d4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconContrast =IconData(0xe9d5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBrightnessContrast =IconData(0xe9d6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStarEmpty =IconData(0xe9d7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStarHalf =IconData(0xe9d8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStarFull =IconData(0xe9d9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHeart =IconData(0xe9da, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHeartBroken =IconData(0xe9db, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMan =IconData(0xe9dc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWoman =IconData(0xe9dd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconManWoman =IconData(0xe9de, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHappy =IconData(0xe9df, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHappy2 =IconData(0xe9e0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSmile =IconData(0xe9e1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSmile2 =IconData(0xe9e2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTongue =IconData(0xe9e3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTongue2 =IconData(0xe9e4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSad =IconData(0xe9e5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSad2 =IconData(0xe9e6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWink =IconData(0xe9e7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWink2 =IconData(0xe9e8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGrin =IconData(0xe9e9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGrin2 =IconData(0xe9ea, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCool =IconData(0xe9eb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCool2 =IconData(0xe9ec, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAngry =IconData(0xe9ed, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAngry2 =IconData(0xe9ee, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEvil =IconData(0xe9ef, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEvil2 =IconData(0xe9f0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShocked =IconData(0xe9f1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShocked2 =IconData(0xe9f2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBaffled =IconData(0xe9f3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBaffled2 =IconData(0xe9f4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconConfused =IconData(0xe9f5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconConfused2 =IconData(0xe9f6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNeutral =IconData(0xe9f7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNeutral2 =IconData(0xe9f8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHipster =IconData(0xe9f9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHipster2 =IconData(0xe9fa, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWondering =IconData(0xe9fb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWondering2 =IconData(0xe9fc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSleepy =IconData(0xe9fd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSleepy2 =IconData(0xe9fe, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFrustrated =IconData(0xe9ff, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFrustrated2 =IconData(0xea00, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCrying =IconData(0xea01, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCrying2 =IconData(0xea02, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpointUp =IconData(0xea03, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpointRight =IconData(0xea04, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpointDown =IconData(0xea05, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpointLeft =IconData(0xea06, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWarning =IconData(0xea07, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNotification =IconData(0xea08, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconQuestion =IconData(0xea09, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconplus =IconData(0xea0a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMinus =IconData(0xea0b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconInfo =IconData(0xea0c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCancelCircle =IconData(0xea0d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBlocked =IconData(0xea0e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCross =IconData(0xea0f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCheckmark =IconData(0xea10, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCheckmark2 =IconData(0xea11, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpellCheck =IconData(0xea12, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEnter =IconData(0xea13, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconExit =IconData(0xea14, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconplay2 =IconData(0xea15, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpause =IconData(0xea16, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStop =IconData(0xea17, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconprevious =IconData(0xea18, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNext =IconData(0xea19, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBackward =IconData(0xea1a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconForward2 =IconData(0xea1b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconplay3 =IconData(0xea1c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpause2 =IconData(0xea1d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStop2 =IconData(0xea1e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBackward2 =IconData(0xea1f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconForward3 =IconData(0xea20, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFirst =IconData(0xea21, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLast =IconData(0xea22, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconprevious2 =IconData(0xea23, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNext2 =IconData(0xea24, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEject =IconData(0xea25, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeHigh =IconData(0xea26, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeMedium =IconData(0xea27, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeLow =IconData(0xea28, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeMute =IconData(0xea29, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeMute2 =IconData(0xea2a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeIncrease =IconData(0xea2b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVolumeDecrease =IconData(0xea2c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLoop =IconData(0xea2d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLoop2 =IconData(0xea2e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconInfinite =IconData(0xea2f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShuffle =IconData(0xea30, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowUpLeft =IconData(0xea31, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowUp =IconData(0xea32, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowUpRight =IconData(0xea33, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowRight =IconData(0xea34, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowDownRight =IconData(0xea35, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowDown =IconData(0xea36, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowDownLeft =IconData(0xea37, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowLeft =IconData(0xea38, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowUpLeft2 =IconData(0xea39, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowUp2 =IconData(0xea3a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowUpRight2 =IconData(0xea3b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowRight2 =IconData(0xea3c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowDownRight2 =IconData(0xea3d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowDown2 =IconData(0xea3e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowDownLeft2 =IconData(0xea3f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconArrowLeft2 =IconData(0xea40, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCircleUp =IconData(0xea41, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCircleRight =IconData(0xea42, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCircleDown =IconData(0xea43, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCircleLeft =IconData(0xea44, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTab =IconData(0xea45, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMoveUp =IconData(0xea46, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMoveDown =IconData(0xea47, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSortAlphaAsc =IconData(0xea48, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSortAlphaDesc =IconData(0xea49, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSortNumericAsc =IconData(0xea4a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSortNumbericDesc =IconData(0xea4b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSortAmountAsc =IconData(0xea4c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSortAmountDesc =IconData(0xea4d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCommand =IconData(0xea4e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShift =IconData(0xea4f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCtrl =IconData(0xea50, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconOpt =IconData(0xea51, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCheckboxChecked =IconData(0xea52, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCheckboxUnchecked =IconData(0xea53, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRadioChecked =IconData(0xea54, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRadioChecked2 =IconData(0xea55, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRadioUnchecked =IconData(0xea56, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCrop =IconData(0xea57, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMakeGroup =IconData(0xea58, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUngroup =IconData(0xea59, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconScissors =IconData(0xea5a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFilter =IconData(0xea5b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFont =IconData(0xea5c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLigature =IconData(0xea5d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLigature2 =IconData(0xea5e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTextHeight =IconData(0xea5f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTextWidth =IconData(0xea60, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFontSize =IconData(0xea61, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBold =IconData(0xea62, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconUnderline =IconData(0xea63, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconItalic =IconData(0xea64, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStrikethrough =IconData(0xea65, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconOmega =IconData(0xea66, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSigma =IconData(0xea67, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpageBreak =IconData(0xea68, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSuperscript =IconData(0xea69, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSubscript =IconData(0xea6a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSuperscript2 =IconData(0xea6b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSubscript2 =IconData(0xea6c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTextColor =IconData(0xea6d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpagebreak =IconData(0xea6e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconClearFormatting =IconData(0xea6f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTable =IconData(0xea70, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTable2 =IconData(0xea71, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconInsertTemplate =IconData(0xea72, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpilcrow =IconData(0xea73, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLtr =IconData(0xea74, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRtl =IconData(0xea75, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSection =IconData(0xea76, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconparagraphLeft =IconData(0xea77, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconparagraphCenter =IconData(0xea78, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconparagraphRight =IconData(0xea79, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconparagraphJustify =IconData(0xea7a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconIndentIncrease =IconData(0xea7b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconIndentDecrease =IconData(0xea7c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShare =IconData(0xea7d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNewTab =IconData(0xea7e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEmbed =IconData(0xea7f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEmbed2 =IconData(0xea80, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTerminal =IconData(0xea81, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconShare2 =IconData(0xea82, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMail =IconData(0xea83, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMail2 =IconData(0xea84, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMail3 =IconData(0xea85, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconMail4 =IconData(0xea86, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAmazon =IconData(0xea87, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogle =IconData(0xea88, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogle2 =IconData(0xea89, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogle3 =IconData(0xea8a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogleplus =IconData(0xea8b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogleplus2 =IconData(0xea8c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogleplus3 =IconData(0xea8d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHangouts =IconData(0xea8e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGoogleDrive =IconData(0xea8f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFacebook =IconData(0xea90, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFacebook2 =IconData(0xea91, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconInstagram =IconData(0xea92, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWhatsapp =IconData(0xea93, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSpotify =IconData(0xea94, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTelegram =IconData(0xea95, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTwitter =IconData(0xea96, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVine =IconData(0xea97, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVk =IconData(0xea98, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRenren =IconData(0xea99, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSinaWeibo =IconData(0xea9a, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRss =IconData(0xea9b, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconRss2 =IconData(0xea9c, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconYoutube =IconData(0xea9d, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconYoutube2 =IconData(0xea9e, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTwitch =IconData(0xea9f, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVimeo =IconData(0xeaa0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconVimeo2 =IconData(0xeaa1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLanyrd =IconData(0xeaa2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFlickr =IconData(0xeaa3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFlickr2 =IconData(0xeaa4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFlickr3 =IconData(0xeaa5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFlickr4 =IconData(0xeaa6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDribbble =IconData(0xeaa7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBehance =IconData(0xeaa8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBehance2 =IconData(0xeaa9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDeviantart =IconData(0xeaaa, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSteam =IconData(0xeaac, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSteam2 =IconData(0xeaad, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDropbox =IconData(0xeaae, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconOnedrive =IconData(0xeaaf, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGithub =IconData(0xeab0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconNpm =IconData(0xeab1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBasecamp =IconData(0xeab2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTrello =IconData(0xeab3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWordpress =IconData(0xeab4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconJoomla =IconData(0xeab5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEllo =IconData(0xeab6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBlogger =IconData(0xeab7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconBlogger2 =IconData(0xeab8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTumblr =IconData(0xeab9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTumblr2 =IconData(0xeaba, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconYahoo =IconData(0xeabb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconYahoo2 =IconData(0xeabc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconTux =IconData(0xeabd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAppleinc =IconData(0xeabe, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFinder =IconData(0xeabf, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconAndroid =IconData(0xeac0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWindows =IconData(0xeac1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWindows8 =IconData(0xeac2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSoundcloud =IconData(0xeac3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSoundcloud2 =IconData(0xeac4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSkype =IconData(0xeac5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconReddit =IconData(0xeac6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHackernews =IconData(0xeac7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconWikipedia =IconData(0xeac8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLinkedin =IconData(0xeac9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLinkedin2 =IconData(0xeaca, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLastfm =IconData(0xeacb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLastfm2 =IconData(0xeacc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconDelicious =IconData(0xeacd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStumbleupon =IconData(0xeace, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStumbleupon2 =IconData(0xeacf, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconStackoverflow =IconData(0xead0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpinterest =IconData(0xead1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpinterest2 =IconData(0xead2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconXing =IconData(0xead3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconXing2 =IconData(0xead4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFlattr =IconData(0xead5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFoursquare =IconData(0xead6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconYelp =IconData(0xead7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconpaypal =IconData(0xead8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconChrome =IconData(0xead9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFirefox =IconData(0xeada, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconIE =IconData(0xeadb, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconEdge =IconData(0xeadc, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSafari =IconData(0xeadd, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconOpera =IconData(0xeade, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFilepdf =IconData(0xeadf, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileOpenoffice =IconData(0xeae0, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileWord =IconData(0xeae1, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconFileExcel =IconData(0xeae2, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconLibreoffice =IconData(0xeae3, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHtmlFive =IconData(0xeae4, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconHtmlFive2 =IconData(0xeae5, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCss3 =IconData(0xeae6, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconGit =IconData(0xeae7, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconCodepen =IconData(0xeae8, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconSvg =IconData(0xeae9, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  static const IconData libIconIcoMoon =IconData(0xeaea, fontFamily: LibFonts.libDefaultIcomoon, matchTextDirection: true ,fontPackage: baseUi);
  //字体图标 end
}